# Generated by Django 4.1 on 2023-07-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rg',
            field=models.CharField(max_length=9),
        ),
    ]
