# Generated by Django 4.1 on 2023-07-27 14:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_student_photo'),
    ]
