# Generated by Django 4.1 on 2023-07-27 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
    ]
